[workspace]
members = [
  "agama-cli",
  "agama-server",
  "agama-lib",
  "agama-locale-data",
  "libzypp",
  "libzypp/zypp-sys",
]

resolver = "2"

[workspace.package]
rust-version = "1.74"
edition = "2021"
