[workspace]
members = [
  "agama-cli",
  "agama-server",
  "agama-lib",
  "agama-locale-data",
  "xtask",
]
resolver = "2"

[workspace.package]
# IpAddr::to_canonical is stable since 1.75
rust-version = "1.75"
edition = "2021"
