name: Submit cockpit-agama

on:
  # runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      # run only when a web frontend source is changed
      - web/**

  # allow running manually
  workflow_dispatch:

jobs:
  update_staging:
    uses: ./.github/workflows/obs-staging-shared.yml
    # pass all secrets
    secrets: inherit
    with:
      install_packages: obs-service-node_modules
      package_name: cockpit-agama
      service_file: web/package/_service
