name: Submit rubygem-agama-yast

on:
  # runs on pushes targeting the default branch
  push:
    branches:
      - master
      - release
    paths:
      # run only when a service source is changed
      - service/**
      - Rakefile

  # allow running manually
  workflow_dispatch:

jobs:
  update_service:
    uses: ./.github/workflows/obs-service-shared.yml
    # pass all secrets
    secrets: inherit
