name: Submit agama-playwright

on:
  # runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      # run only when a Playwright source is changed
      - playwright/**

  # allow running manually
  workflow_dispatch:

jobs:
  update_staging:
    uses: ./.github/workflows/obs-staging-shared.yml
    # pass all secrets
    secrets: inherit
    with:
      package_name: agama-playwright
      service_file: playwright/package/_service
