[options]
library = "Zypp"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
girs_directories = ["gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
  "Zypp.Context",
  "Zypp.Exception"
]

manual = [
  "GLib.Error",
  "GLib.Quark"
]
